server:
  port: 9527
spring:
  application:
    name: hello-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: hello_emp #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://hello_emp
          predicates:
            - Path=/hello/emp/**   #断言,路径相匹配的进行路由

        - id: hello_dept
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://hello_dept
          predicates:
            - Path=/hello/dept/**   #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: hello-gateway
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


